name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main","develop" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make
      run: make -j
